# Generated by Django 6.0.2 on 2026-03-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('TRANSPORT', 'transport'), ('ENTERTAINMENT', 'entertainment'), ('HEALTH', 'health'), ('BILLS', 'Bills'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('TRANSPORT', 'transport'), ('ENTERTAINMENT', 'entertainment'), ('HEALTH', 'health'), ('BILLS', 'Bills'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
